name: $(Build.Version.Number).$(Build.BuildId)

trigger:
- aks-task1-k8s

resources:
- repo: self

variables:
- template: version.yml
- name: Build.Version.Number
  value: ${{ variables.version }}
- name: dockerRegistryServiceConnection
  value: $(dockerRegistryServiceConnection)
- name: imageRepository
  value: $(imageRepository)
- name: containerRegistry
  value: $(containerRegistry)
- name: dockerfilePath
  value:  '**/Dockerfile'
- name: vmImageName 
  value: 'ubuntu-latest'
  
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          ${{ variables.version }}.$(Build.BuildId)

    - upload: manifests
      artifact: manifests

# - stage: Deploy
#   displayName: Deploy stage
#   dependsOn: Build

#   jobs:
#   - deployment: Deploy
#     displayName: Deploy
#     pool:
#       vmImage: $(vmImageName)
#     environment: $(environment)
#     strategy:
#       runOnce:
#         deploy:
#           steps:
